apiVersion: v1
kind: Service
metadata:
  name: auth-svc
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - port: 9000
      name: server
      protocol: TCP
      targetPort: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth
          image: auth
          imagePullPolicy: Never
          env:
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  key: secret
                  name: app-jwt-secret
            - name: ISS
              valueFrom:
                secretKeyRef:
                  key: key
                  name: app-jwt-secret
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 9000
