apiVersion: v1
kind: Service
metadata:
  name: joke-svc
  annotations:
    konghq.com/protocol: grpc
spec:
  type: ClusterIP
  selector:
    app: joke-service
  ports:
    - port: 9000
      name: grpc
      protocol: TCP
      targetPort: 9000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: joke-service
spec:
  selector:
    matchLabels:
      app: joke-service
  template:
    metadata:
      labels:
        app: joke-service
    spec:
      containers:
        - name: joke
          image: jokes
          imagePullPolicy: Never
          env:
            - name: SECRET
              value: super-secret-key
            - name: ISS
              value: jwt-issuer-2
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 9000
